---
abstract: unknown
author:
  - 'Diab Jerius'
build_requires:
  Devel::FindPerl: '0'
  ExtUtils::MakeMaker: '6.36'
  File::pushd: '0'
  Test::Base: '0'
  Test::Deep: '0'
  Test::Exception: '0'
  Test::File: '0'
  Test::Lib: '0'
  Test::More: '0'
  Test::Most: '0'
  Test::Trap: '0'
configure_requires:
  CPAN::Meta: '0'
  ExtUtils::MakeMaker: '6.36'
dynamic_config: '0'
generated_by: 'Module::Install version 1.10, CPAN::Meta::Converter version 2.131560'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: IPC-PrettyPipe
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  IO::ReStoreFH: '0.04'
  IPC::Run: '0'
  List::MoreUtils: '0'
  List::Util: '1.34'
  Module::Load: '0'
  Module::Runtime: '0'
  Moo: '1.001000'
  MooX::Attributes::Shadow: '0'
  Safe::Isa: '0'
  String::ShellQuote: '0'
  Template::Tiny: '0'
  Term::ANSIColor: '0'
  Try::Tiny: '0'
  Type::Tiny: '0.038'
  parent: '0'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=IPC-PrettyPipe
  repository: http://bitbucket.org/djerius/ipc-prettypipe
version: '0.03'
